### ISSUE TITLE
Revamp the overview page

### ISSUE THREAD

**Issue by himanshugarg06** [bcnmy/docs#217]
- [ ] Provide clear explanations of the product offerings
- [ ] Improve navigation from the overview page
- [ ] Remove all the images. paymaster images are already part of the paymaster documentation. 
- [ ] Add a demo, showcasing the UX improvements using privy.
- [ ] add npm i sdk-package to showcase, add redirection to the quickstart page

**Comment by bicoxdesign** [comment]
We have some old designs from the last year. Please take it all with a pinch of salt since they were not informed by solid PRDs.

_Also, please note that the components within the layouts such as paymaster cards, buttons, title styles, et al have also changed over time. We use cleaner, more relevant internal components now._

---
### 1. Overview Concept

[Figma Board for Overview](https://www.figma.com/file/6NZtA8wz5L3mCk472g9qlQ/%F0%9F%9B%A0%EF%B8%8F-2023-Workshop?type=design&node-id=4878%3A29071&mode=design&t=lauHlLCa3cjf1Jye-1) `September 2023`

#### Philosophy/How this was designed
This was made to show all key information clearly, helping you make decisions quickly. I wanted to display important metrics in an organised way so that 1) developers feel confident everything is working fine, and 2) the call-to-action buttons (CTAs) save time by acting as direct shortcuts to tasks that are usually buried deeper in the system.
___
![overview-existing-user](https://github.com/bcnmy/docs/assets/159017945/12dcabcf-cf94-4cbd-9238-78d0c041fc07)

---
### 2. Navigation Concept
[Figma Board for Navigation](https://www.figma.com/file/6NZtA8wz5L3mCk472g9qlQ/%F0%9F%9B%A0%EF%B8%8F-2023-Workshop?type=design&node-id=5982%3A25577&mode=design&t=lauHlLCa3cjf1Jye-1) `November 2023`

#### Philosophy/How this was designed
Inspired by Vercel, this design highlights all the important links more prominently, making better use of the space that the left navigation currently occupies without much benefit. With this new approach, we could comfortably introduce a fourth level of navigation. Right now, we're limited to using three levels effectively.
___
![account-settings](https://github.com/bcnmy/docs/assets/159017945/8ce58783-4c9a-46ca-9230-7e9328eb8778)
___
![paymaster-list](https://github.com/bcnmy/docs/assets/159017945/982f5bd0-f92c-46c2-b4a7-a0df70e2ce4b)
___
☠️ End of update ☠️

**Comment by NunoFilipeSantos** [comment]
@bicoxdesign , I believe @himanshugarg06 here is talking about the overview on Docs (this repository), not the Dashboard.

I have refined a bit the original ticket, please complete it with your thoughts @himanshugarg06 .

**Comment by Graeme-Code** [comment]
Hi @himanshugarg06 . 

I think the points you have are good. Looking at the analytics here: 
https://analytics.google.com/analytics/web/
<img width="659" alt="Screenshot 2024-03-04 at 16 20 27" src="https://github.com/bcnmy/docs/assets/7915365/8fa84058-64f5-43b6-a327-79c84dc91e17">
?utm_source=scheduled_report#/analysis/p427722938/edit/0K9oREacReuSdPPLf9b0FA

I think additions to the overview page which would be helpful:
- Link supported networks (If dev's network is not supported, they might as well stop looking) (this was third most visited page after a session started)

**Comment by AhmedBalaghi** [comment]
Agreed with the points. 
In terms of the demo, id say lets be creative here and not just copy zerodev. We of course dont need to show lots of crazy things but what if it can be seqentiak. Heres gasless nft mint, heres pay gas in a different token, heres xyz.
