### ISSUE TITLE
Modes of Paymaster seems unclear

### ISSUE THREAD

**Issue by B-Venkatesh7210** [bcnmy/docs#222]
### How could we improve the Biconomy documentation site?

I think we should have 2 different sections along with "Integration" in Paymaster. The sections should be "Sponsored" and "ERC20", and in each one of them integration of modes should be explained respectively. In the current scenario, we have spoken about feeQuotes and response at the beginning of "Methods" section and have defined modes below it, which is quite confusing and unclear.

**Comment by himanshugarg06** [comment]
so these pages are for paymaster package integration, are you looking for a paymaster only flow methods integration example? 
smart account already have these calls integrated in the sendTransaction.

**Comment by himanshugarg06** [comment]
The core problems are below
1. **Users are unable to understand if in order to use the SDK, do they need to check the paymaster and bundler sections also.**
Restructure the docs to showcase Account abstraction SDK in such a way that its intuitive that one doesn't need bundler or paymaster package/ methods to use the SDK 
2. **Tutorials are not visible - for example the gasless and ERC20 tutorials are not visible directly.**
Mention in the quickstart and overview 
3. **Method param definition like maxApproval**
Add references to the tech documentation (tsDocs) and improve tsDocs for param definitions, given there are a lot of params in each method

Apart from these we can mention in the Overview page, how to use docs.
